language: ruby
rvm:
  - "2.1.5"
  - "2.1.0"
  - "2.0.0"
env:
  - DB=mysql
  - DB=postgresql
gemfile:
  - gemfiles/Gemfile.rails-3.2.x
  - gemfiles/Gemfile.rails-4.2.x
  - gemfiles/Gemfile.rails-edge
script:
  - gem install bundler
  - bundle install
  - bundle exec rake spec